apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- service.yaml
- ingress.yaml

patches:
- path: deployment_patch.yaml
  target:
    kind: StatefulSet
    name: pv-poc-statefulset


labels:
- includeSelectors: true
  pairs:
    app: pv-poc