package eu.europeana.thumbnail.web;

import eu.europeana.features.S3Object;
import eu.europeana.thumbnail.model.ImageSize;
import eu.europeana.thumbnail.model.MediaStream;
import eu.europeana.thumbnail.service.StoragesService;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.validation.constraints.Pattern;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.Strings;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.core.io.InputStreamResource;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.context.request.WebRequest;

import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

/**
 * Retrieves image thumbnails.
 * The Thumbnail API doesn't require any form of authentication, providing an API key is optional.
 * We allow the user setting an extension like .png or .jpg, but we (mostly) ignore this and simply return the image in
 * the format as it was stored in S3
 */
@RestController
@Validated
public class ThumbnailControllerV2 extends AbstractController {

    private static final Logger LOG = LogManager.getLogger(ThumbnailControllerV2.class);

    private static final long CONTENT_LENGTH_IMAGE_ICON = 2319;
    private static final long CONTENT_LENGTH_SOUND_ICON = 2484;
    private static final long CONTENT_LENGTH_VIDEO_ICON = 1932;
    private static final long CONTENT_LENGTH_TEXT_ICON  = 2180;
    private static final long CONTENT_LENGTH_3D_ICON    = 3012;

    protected static final String  INVALID_URL_MESSAGE = "INVALID URL";

    public ThumbnailControllerV2(StoragesService storagesService) {
        super(storagesService);
    }

    /**
     * Retrieves image thumbnails.
     *
     * @param url  optional, the URL of the media resource of which a thumbnail should be returned. Note that the URL
     *             should be encoded. When no url is provided a default thumbnail will be returned
     * @param size optional, the size of the thumbnail, can either be w200 (width 200) or w400 (width 400).
     * @param type optional, type of the default thumbnail (media image) in case the thumbnail does not exists or no url is provided,
     *             can be: IMAGE, SOUND, VIDEO, TEXT or 3D.
     * @param webRequest auto-generated by Spring Boot
     * @param request auto-generated by Spring Boot
     * @param response auto-generated bySpring Boot
     * @return responseEntity
     */
    @GetMapping(value = {"/api/v2/thumbnail-by-url.json", "/thumbnail/v2/url.json"})
    @SuppressWarnings("javasecurity:S5145") // we only log for debug purposes, plus we validate the user input
    public ResponseEntity<InputStreamResource> thumbnailByUrlV2(
            @RequestParam(value = "uri")
                @Pattern(regexp = "^((https?|ftp)://|urn:).*$", message = INVALID_URL_MESSAGE) String url,
            @RequestParam(value = "size", required = false, defaultValue = "w400") String size,
            @RequestParam(value = "type", required = false, defaultValue = "IMAGE") String type,
            WebRequest webRequest, HttpServletRequest request, HttpServletResponse response) {
        long startTime = 0;
        if (LOG.isDebugEnabled()) {
            startTime = System.nanoTime();
            LOG.debug("Url = {}, size = {}, type = {}", url, size, type);
        }

        Optional<MediaStream> mediaFile = retrieveThumbnail(request, null, url, getWidth(size));
        ResponseEntity<InputStreamResource> result;
        // if there is no image, we return the default 'type' icon
        if (mediaFile.isEmpty()) {
            result = generateResponse(webRequest, response, getDefaultThumbnailForNotFoundResourceByType(type));
        } else {
            result = generateResponse(webRequest, response, mediaFile.get());
        }

        if (LOG.isDebugEnabled()) {
            logRequestDuration(startTime, "Url = " + url + ", status = " + response.getStatus());
        }
        return result;
    }

    private int getWidth(String size) {
        if (Strings.CI.equals(size, "w200") || Strings.CI.equals(size, "200")) {
            return ImageSize.MEDIUM.getWidth();
        }
        return ImageSize.LARGE.getWidth();
    }

    private MediaStream getDefaultThumbnailForNotFoundResourceByType(final String type) {
        String defaultImageName;
        long defaultImageContentLength;
        switch (StringUtils.upperCase(type)) {
            case "IMAGE" -> {
                defaultImageName = "EU_thumbnails_image.png";
                defaultImageContentLength = CONTENT_LENGTH_IMAGE_ICON;
            }
            case "SOUND" -> {
                defaultImageName = "EU_thumbnails_sound.png";
                defaultImageContentLength = CONTENT_LENGTH_SOUND_ICON;
            }
            case "VIDEO" -> {
                defaultImageName = "EU_thumbnails_video.png";
                defaultImageContentLength = CONTENT_LENGTH_VIDEO_ICON;
            }
            case "TEXT" -> {
                defaultImageName = "EU_thumbnails_text.png";
                defaultImageContentLength = CONTENT_LENGTH_TEXT_ICON;
            }
            case "3D" -> {
                defaultImageName = "EU_thumbnails_3d.png";
                defaultImageContentLength = CONTENT_LENGTH_3D_ICON;
            }
            default -> {
                defaultImageName = "EU_thumbnails_image.png";
                defaultImageContentLength = CONTENT_LENGTH_IMAGE_ICON;
            }
        }
        InputStream stream = this.getClass().getResourceAsStream("/images/" + defaultImageName);
        Map<String, Object> metadata = new HashMap<>();
        metadata.put(S3Object.CONTENT_LENGTH, defaultImageContentLength);
        return new MediaStream(null, defaultImageName, new S3Object(stream, metadata));
    }

}
