package eu.europeana.thumbnail.web;

import eu.europeana.api.commons_sb3.error.EuropeanaApiException;
import eu.europeana.thumbnail.exception.ThumbnailInvalidUrlException;
import eu.europeana.thumbnail.exception.ThumbnailNotFoundException;
import eu.europeana.thumbnail.model.MediaStream;
import eu.europeana.thumbnail.service.StoragesService;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.validation.constraints.Pattern;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.core.io.InputStreamResource;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.context.request.WebRequest;

import java.util.Optional;

/**
 * Retrieves image thumbnails for version 3
 * The thumbnail API doesn't require any form of authentication, providing an API key is optional.
 * Note that the controller can return content in PNG and JPG format, depending on the format of the thumbnail that is
 * requested (extension parameter)
 */
@RestController
@RequestMapping("/thumbnail")
@Validated
public class ThumbnailControllerV3 extends AbstractController {

    private static final Logger LOG = LogManager.getLogger(ThumbnailControllerV3.class);

    protected static final String SIZE_ERROR_MESSAGE = "Invalid size. Supported values are 200 and 400";

    protected static final String ID_ERROR_MESSAGE = "Invalid or empty id";

    protected static final String URL_ERROR_MESSAGE = "Either Size or Id is missing. Correct url is /v3/{size}/{id}";

    /**
     * Create a new controller to server Thumbnail V3 requests
     * @param storagesService the storage service to use
     */
    public ThumbnailControllerV3(StoragesService storagesService) {
        super(storagesService);
    }

    /**
     * Endpoint to make sure we return a 400 for invalid urls like '/thumbnail/v3/200/', '/thumbnail/v3//xyz.jpg'
     * @throws ThumbnailInvalidUrlException always for this endpoint
     * @return 400 bad Request
     */
    @SuppressWarnings("java:S6856") // no point in binding {id} to a variable
    @GetMapping(value = {"/v3/{id}", "/v3/{id}/", "/v3//{id}", "/v3//{id}/"})
    public ResponseEntity<InputStreamResource> thumbnailByUrlV3InvalidUrl() throws ThumbnailInvalidUrlException {
        throw new ThumbnailInvalidUrlException(URL_ERROR_MESSAGE);
    }

    /**
     * Endpoint to make sure we return a 400 for invalid urls like '/thumbnail/v3/', '/thumbnail/v3', '/thumbnail/v3//'
     * @throws ThumbnailInvalidUrlException always for this endpoint
     * @return 400 Bad Request
     */
    @GetMapping(value = {"/v3", "/v3/"})
    public ResponseEntity<InputStreamResource> thumbnailByUrlV3EmptyUrl() throws ThumbnailInvalidUrlException {
        throw new ThumbnailInvalidUrlException(URL_ERROR_MESSAGE);
    }

    /**
     * Retrieves image thumbnails.
     *
     * @param size the size of the thumbnail, currently we support 200 (width 200px) or 400 (width 400px).
     * @param id the id of the file (MD5 hash of original url)
     * @param webRequest auto-generated by Spring Boot
     * @param request auto-generated by Spring Boot
     * @param response auto-generated bySpring Boot
     * @throws EuropeanaApiException when there is a problem retrieving data
     * @return responseEntity
     */
    @GetMapping(value = {"/v3/{size}/{id}", "v3/{size}/{id}/"})
    @SuppressWarnings("javasecurity:S5145") // we only log for debug purposes, plus we validate the user input
    public ResponseEntity<InputStreamResource> thumbnailByUrlV3(
            @PathVariable(value = "size", required = false)
                @Pattern(regexp = "^(200|400)$", message = SIZE_ERROR_MESSAGE) String size,
            @PathVariable(value = "id")
                @Pattern(regexp = "^[a-fA-F0-9]{8,128}((?i).jpg|.jpeg|.png|.webp)?$", message = ID_ERROR_MESSAGE) String id,
            WebRequest webRequest, HttpServletRequest request, HttpServletResponse response) throws EuropeanaApiException {
        long startTime = 0;
        if (LOG.isDebugEnabled()) {
            startTime = System.nanoTime();
            LOG.debug("Thumbnail id = {}, size = {}", id, size);
        }

        int extensionStart = id.lastIndexOf('.');
        String idWithoutExtension;
        String extension = null;
        if (extensionStart > 0) {
            idWithoutExtension = id.substring(0, extensionStart);
            extension = id.substring(extensionStart);
            LOG.debug("Thumbnail cleaned id = {}, extension = {}", idWithoutExtension, extension);
        } else {
            idWithoutExtension = id;
        }

        Optional<MediaStream> mediaFile = retrieveThumbnail(request, idWithoutExtension, extension, Integer.valueOf(size));
        if (mediaFile.isEmpty()) {
            if (LOG.isDebugEnabled()) {
                logRequestDuration(startTime, "Id = " + id + ", status = " + HttpStatus.NOT_FOUND);
            }
            throw new ThumbnailNotFoundException();
        }
        ResponseEntity<InputStreamResource> result = generateResponse(webRequest, response, mediaFile.get());
        if (LOG.isDebugEnabled()) {
            logRequestDuration(startTime, "Id = " + id + ", status = " + response.getStatus());
        }
        return result;
    }
}
