apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbnail-api-deployment
spec:
  # selector.matchLabels is provided via Kustomize
  template:
    spec:
      containers:
        - name: thumbnail-api
          image: europeana/thumbnail-api
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 50
            periodSeconds: 20
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 50
            periodSeconds: 20
          volumeMounts:
            - name: secret
              mountPath: "/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/thumbnail.user.properties"
              readOnly: true
              subPath: thumbnail.user.properties
      volumes:
        - name: secret
          secret:
            secretName: thumbnail-api-secret
