apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

labels:
  - includeSelectors: true
    pairs:
      app: pv-poc

# expects files to be in the same directory
secretGenerator:
  - name: pv-poc-secret
    files:
      - thumbnail.user.properties
